### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by gzliudan** [OpenLeverageDev/openleverage-contracts#39]
Maybe there are some errors in document. According to README.md, test command is `truffle test`. But when I run ganache-cli: `ganache-cli` first, then run command `npx truffle test`, below error occurs:
```text
Using network 'development'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Deploying in network = development
Error: Could not find artifacts for UniswapV2Factory from any sources
    at Resolver.require (/home/xxx/openleverage-contracts/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)
    at Object.require (/home/xxx/openleverage-contracts/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:275:1)
    at Object.<anonymous> (/home/xxx/openleverage-contracts/test/EthDexAggergatorTaxToken.js:3:36)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/xxx/openleverage-contracts/node_modules/truffle/node_modules/mocha/lib/mocha.js:390:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/xxx/openleverage-contracts/node_modules/truffle/node_modules/mocha/lib/mocha.js:387:14)
    at Mocha.run (/home/xxx/openleverage-contracts/node_modules/truffle/node_modules/mocha/lib/mocha.js:961:10)
    at /home/xxx/openleverage-contracts/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:151:1
    at new Promise (<anonymous>)
    at Object.run (/home/xxx/openleverage-contracts/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:150:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/home/xxx/openleverage-contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/index.js:177:1)
    at Command.run (/home/xxx/openleverage-contracts/node_modules/truffle/build/webpack:/packages/core/lib/command.js:172:1)
Truffle v5.4.7 (core: 5.4.7)
Node v16.14.2
```
The document should provides right and full instructions for users.

**Comment by jimmy-openlev** [comment]
Please always take a look at the latest version of the Action script for detailed steps.

https://github.com/OpenLeverageDev/openleverage-contracts/blob/main/.github/workflows/node.js.yml
